### ISSUE TITLE
Can I use sql queries to get a table?

### ISSUE THREAD

**Issue by EagleChen** [siddontang/go-mysql-elasticsearch#10]
I can only get original tables by using table name in `Source`.

Can I use sql queries to fetch a table? One of the advantage of SQL queries is the join operation. From many tables, new tuples can be formed.

You can find an example [here](https://github.com/jprante/elasticsearch-jdbc#structured-objects)

**Comment by siddontang** [comment]
We use mysql row format binlog to sync mysql changed into other places, and we only care origin table changes. If no data changes, we cannot sync. 

So we don't support select now.

**Comment by EagleChen** [comment]
Then can we specify `parent / child` relationship ?

Check [here](http://stackoverflow.com/questions/21007710/elasticsearch-set-up-parent-child-using-jdbc-rivers) for the example.

**Comment by siddontang** [comment]
Maybe you can customize your own field mapping to support this feature, but I have not used hierarchical   data mode in ES before, and I don't know whether it can be ok or not.

**Comment by EagleChen** [comment]
AFAIK, to use hierarchical data in the latest ES, when inserting data, I need to use the following command
```
curl -XPUT  host:port/index/type?parent=some_parent_id
```

When using `bulk` api, I need to set `_parent` in the index part.

More information can be found [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html).

But there is no configuration in "river.toml" file for this purpose.

I'm wondering whether you can support this scenario.
Thanks!

**Comment by siddontang** [comment]
Seem a hard work, and now I don't have enough time to do this, sorry for that. 
And at first, I must know how to use parent-child mapping :-)

**Comment by EagleChen** [comment]
OK. I understand.
Thanks.
