### ISSUE TITLE
data length < expected

### ISSUE THREAD

**Issue by WangXiangUSTC** [siddontang/go-mysql-elasticsearch#101]
2017/04/17 21:19:42 binlogstreamer.go:47: [error] close sync with err: data len 4553 < expected 4644
2017/04/17 21:19:42 canal.go:150: [error] canal start sync binlog err: data len 4553 < expected 4644

This will be happen occasionally, and restart go-mysql-elasticsearch this error will also exist.

**Comment by siddontang** [comment]
seem your binlog is corrupted, the length in the binlog event header is not equal to the real length of the event. I will add more detailed log to show the filename and offset for the event later.

**Comment by siddontang** [comment]
This error is caused when parsing JSON field. can you use the go-mysqlbinlog tool to sync the binlog from the position saved in your configured meta file?

**Comment by siddontang** [comment]
@WangXiangUSTC 

You can use the newest master to have a try.

**Comment by WangXiangUSTC** [comment]
great，I will try tomorrow。
thanks










At 2017-04-18 22:40:44, "siddontang" <notifications@github.com> wrote:


@WangXiangUSTC

You can use the newest master to have a try.

**Comment by WangXiangUSTC** [comment]
I have already run the newest version several days, and this  error no longer occur
