### ISSUE TITLE
About "Don't change too many rows at same time in one SQL"

### ISSUE THREAD

**Issue by chengguangnan** [siddontang/go-mysql-elasticsearch#107]
I have a table with 200 million rows. Will update 1 million rows in one SQL a problem? What would happen?

**Comment by siddontang** [comment]
Hi @chengguangnan 

I have not tested this case before, so maybe you can have a try. In most cases, this may not be a problem, but this transaction is so huge, so if we meet some network error, we may retry this huge transaction again.

**Comment by chengguangnan** [comment]
All good. Thanks!
