### ISSUE TITLE
can't load package  while excuting "go get github.com/siddontang/go-mysql-elasticsearch"

### ISSUE THREAD

**Issue by ebsinori** [siddontang/go-mysql-elasticsearch#108]
can't load package: package github.com/siddontang/go-mysql-elasticsearch: no buildable Go source files in /Users/ebsinori/go/src/github.com/siddontang/go-mysql-elasticsearch

**Comment by siddontang** [comment]
Please refer https://github.com/siddontang/go-mysql-elasticsearch#install

**Comment by ebsinori** [comment]
啊发现自己好蠢……没事了，谢谢

**Comment by icehan2016** [comment]
请问这个问题 如何解决
