### ISSUE TITLE
what's the meaning "binlog must ROW format, but  now"

### ISSUE THREAD

**Issue by fly3q** [siddontang/go-mysql-elasticsearch#12]
binlog must ROW format, but  now
![image](https://cloud.githubusercontent.com/assets/194304/8618470/43e4b5e6-2741-11e5-865e-538514b34dd5.png)

**Comment by siddontang** [comment]
It means that you must set row format for your binlog explicitly, but we don't find its set. 

you can use `SHOW GLOBAL VARIABLES LIKE "binlog_format"` to see what 's the real format.

**Comment by fly3q** [comment]
thx
