### ISSUE TITLE
关于关联关系的处理

### ISSUE THREAD

**Issue by sanguinar** [siddontang/go-mysql-elasticsearch#120]
增量同步中的表与表的关联关系是怎么处理的？是Elasticsearch Parent-Child关系吗？是查询-删除-重建吗？三代以及以上关系怎么处理呢？

**Comment by siddontang** [comment]
什么叫表与表的关联，在 mysql binlog 里面，只有每个 table 的 row 更新。

**Comment by TwoColors** [comment]
就是sql里的jion，希望能在elasticsearch做jion查询，我也考虑到建nested index或者是Parent-Child不太合适，需要查数据什么的。我们这几天做了一个方案是在es查询端用lucene封装了一个插件，目前表现还不错，es端的延迟大概在100多ms。
