### ISSUE TITLE
can't load package while excuting "go get github.com/siddontang/go-mysql-elasticsearch"

### ISSUE THREAD

**Issue by icehan2016** [siddontang/go-mysql-elasticsearch#121]
can't load package while excuting "go get github.com/siddontang/go-mysql-elasticsearch"

求大神解答

**Comment by siddontang** [comment]
see https://github.com/siddontang/go-mysql-elasticsearch#install

**Comment by icehan2016** [comment]
看了很多遍 还是不晓得如何解决

**Comment by siddontang** [comment]
就是不解决，skip
或者你用 git clone 显示 clone 到 GOPATH 下面特定位置
