### ISSUE TITLE
FindAllStringSubmatch  不通过

### ISSUE THREAD

**Issue by dotnet123** [siddontang/go-mysql-elasticsearch#122]
`valuesExp:= regexp.MustCompile("^INSERT INTO `(.+?)` VALUES \\((.+)\\);$")

	sql:="INSERT INTO `so_master` VALUES (20,'cfdd22a4-2222-45b0-8892-40102a49d506','093010046404',5,NULL,40,'2017-03-16 13:46:14',76388,'339590d0-726a-45b5-801d-9371707d0976',15,50,'2,1','2017-03-17 00:00:00','下午','11110487560','11110487560','上海市',0,0,0.00,NULL,NULL,0.00,17.56,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2017-06-07 03:26:42');"

	m := valuesExp.FindAllStringSubmatch(sql, -1)`

这段代码我单独运行没有问题,可是项目中运行总是返回 nil, 如下图,请问是什么原因呢?
![2017-08-07 15-42-26](https://user-images.githubusercontent.com/21954452/29016996-68091dbc-7b87-11e7-8b80-d5d953e54ddd.png)
参数传的都没问题
![2017-08-07 15-46-452](https://user-images.githubusercontent.com/21954452/29017132-1f7717ce-7b88-11e7-9bac-889f5dee4a44.png)

**Comment by siddontang** [comment]
项目中这个 query 打印出来是怎样的？

**Comment by dotnet123** [comment]
我已经找到原因了,因为传进来的sql 以/r 结尾, 所以加上TrimSpace就可以了,可能跟操作系统有关系,我用的是windows10
![qq 20160614144142](https://user-images.githubusercontent.com/21954452/29052427-9f33b6ae-7c1c-11e7-9db2-7bd2a68531d3.png)

**Comment by siddontang** [comment]
Cool @dotnet123 

有一个 PR https://github.com/siddontang/go-mysql/pull/121 处理了 windows，但 CI 过不了。
你可以提个 PR 帮重新 fix 下。
