### ISSUE TITLE
mysqldump同步数据时报错

### ISSUE THREAD

**Issue by jefry86** [siddontang/go-mysql-elasticsearch#125]
canal.go:143: [error] canal dump mysql err: exit status 3

**Comment by siddontang** [comment]
any more detailed message?

**Comment by jefry86** [comment]
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Error 2013: Lost connection to MySQL server during query when dumping table `user_info` at row: 91935

**Comment by siddontang** [comment]
seem that mysqldump can't dump your data, is your table too huge? 
Or how about the keepalive time for your MySQL?

**Comment by jefry86** [comment]
thanks
