### ISSUE TITLE
请问能支持同步远程数据库吗？

### ISSUE THREAD

**Issue by fiht** [siddontang/go-mysql-elasticsearch#146]
# 问题
数据库服务器为独立服务器，可以在数据库服务器上开启 binlog 功能，但是无法在数据库服务器上安装 go-mysql-elasticsearch 插件，请问是否可以在其他服务器上使用 binlog 的方式增量同步 MySQL中的数据？
谢谢！

**Comment by siddontang** [comment]
可以，配置好你的 MySQL address 就 ok，see https://github.com/siddontang/go-mysql-elasticsearch/blob/master/etc/river.toml#L3

**Comment by fiht** [comment]
顺利同步，多谢！
