### ISSUE TITLE
mysql error 1064 when starting

### ISSUE THREAD

**Issue by gogogen** [siddontang/go-mysql-elasticsearch#15]
I encountered the following error when i tried to start:
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"binlog_format"' at line 1

My database is mysql 5.6.22. and the binlog_format is "row".
So could you help me figure this out. Thx

**Comment by siddontang** [comment]
@gogogen, this seems strange to me.

Can you tell the whole log output? 
The error may occur when we run `SHOW GLOBAL VARIABLES LIKE "binlog_format";`, can you run this query directly in your MySQL?

Thanks.

**Comment by gogogen** [comment]
Thanks, I got it. 
Because my database used the `sql_mode = "Oracle"` setting which contains `ANSI_QUOTES` mode. 
I will change my `sql_mode`, but I still recommend you to use single quotation instead of double quotation.
Thank you! This tool is really helpful.

**Comment by siddontang** [comment]
Thank you, I will change it later.:-)
