### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by kobehaha** [siddontang/go-mysql-elasticsearch#150]
## 问题

考虑到一种情况, 当我们存在一主多从的情况下,go-mysql-ealsticsearch是不好扩展的

1 挂在主库，对性能会有影响
2 挂在从库上,只能指定一个从库，当从库挂了,同步工具就需要修复,而且不好直接从其他的从库同步

个人觉得应该考虑一些高可用的方式来增强程序的可扩展性和健壮性

**Comment by siddontang** [comment]
这个只是一个 sync 工具，HA 这些还是上面自己处理好一点。

**Comment by kobehaha** [comment]
好的

**Comment by siddontang** [comment]
如果 syncer 自己要做 HA，我觉得应该是将同步的信息存到 etcd 或者 zk，现在是放到文件的，如果同步的挂了，另一个机器可以从 etcd 继续同步

**Comment by kobehaha** [comment]
这是一种非常好的解决方式，需要部署多个syncer,我觉得就可能引入一些细节问题

1 syncr节点，当一个syncer挂了， syncer 后端节点谁作为backup,是在配置文件中指定，还是也交给etcd,用类似服务注册的方式实现

2 syncer和binlog耦合，那么当syncer挂了，那么其余syncer需要获取同步信息，然后这syncer必须能获取到binlog,可能最简单的方式是直接部署本机，重新读取数据，也可以用类似nfs把binlog映射到其他机器.总之，要求是syncer必须有一种方式读到binlog

其实这种方式已经提高了系统可用性，作为一个同步工具我考虑得可能过多了

**Comment by siddontang** [comment]
你的 binlog 在 mysql 上面，syncer 哪里都能读取
用 etcd 的 election 机制得到一个 syncer leader 就可以了。

其实这些都增加了复杂性，所以做到工具上面有点太重了。
