### ISSUE TITLE
Read Replica RDS

### ISSUE THREAD

**Issue by jvallarvisp** [siddontang/go-mysql-elasticsearch#155]
Why is it Read Replica RDS Instance is not triggering sync?

**Comment by siddontang** [comment]
Can you explain your problem more clearly?

**Comment by LockGit** [comment]
in /etc/river.toml file , the mysql host config must is master ip address, can't slave mysql ip address ?

**Comment by siddontang** [comment]
if your slave mysql has binlog, it can.
