### ISSUE TITLE
How can I sync all table in database?

### ISSUE THREAD

**Issue by perfectacle** [siddontang/go-mysql-elasticsearch#161]
I want to sync all table in database,
How can I??
tables = ["*"]
not working... help me!!

and Can I use ignore table name...?

**Comment by siddontang** [comment]
Sadly, we don't support it now, because I think it is not necessary to sync all tables.

But maybe it is easy to do, you can see https://github.com/siddontang/go-mysql-elasticsearch/blob/master/river/river.go#L142 and change to support it.

Please file a PR.

**Comment by perfectacle** [comment]
Thanks @siddontang,
I will try to PR!
