### ISSUE TITLE
How can I sync table(after re turn on go-mysql-elasticsearch)

### ISSUE THREAD

**Issue by perfectacle** [siddontang/go-mysql-elasticsearch#163]
first time I sync table, everything is ok.
but I terminated go-mysql-elasticsearch, because my mistake.
and I turn on go-mysql-elasticsearch, but It sync row after last sync row,
how can I reset...?
I re-install elasticsearch, but same issue,
How can I fix it...?

**Comment by siddontang** [comment]
you can delete your master.info file which configurated in the data_dir in your config file.

**Comment by perfectacle** [comment]
I remove master.info file, and turn on go-mysql-elasticsearch,
but same... make same master.info file and doesn't sync previous data...

**Comment by siddontang** [comment]
what does your log output?

**Comment by perfectacle** [comment]
ohoh sorry, It works correctly! Thanks!
