### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by huangxiaoye** [siddontang/go-mysql-elasticsearch#170]
os:mac10.12.6
go version:1.9
cross compile macos -> linux64
error message
river/river.go:269:19: r.canal.StartFrom undefined (type *canal.Canal has no field or method StartFrom)

**Comment by siddontang** [comment]
how do you compile it? using `make`?

**Comment by huangxiaoye** [comment]
make
go build -o bin/go-mysql-elasticsearch ./cmd/go-mysql-elasticsearch
# github.com/siddontang/go-mysql-elasticsearch/river
river/river.go:269:19: r.canal.StartFrom undefined (type *canal.Canal has no field or method StartFrom)
make: *** [build-elasticsearch] Error 2

**Comment by siddontang** [comment]
please update
