### ISSUE TITLE
不能指定mysql的socket文件路径

### ISSUE THREAD

**Issue by zslsc18** [siddontang/go-mysql-elasticsearch#188]
mysql服务器启动时，没有使用默认的socket文件路径，导致mysqldump时异常，能不能在配置文件中添加一个配置项用来指定socket文件路径，谢谢。
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by EagleChen** [comment]
@zslsc18 
你有设置`mysql`的 `addr`，`user` 等信息吗？

参考： https://github.com/siddontang/go-mysql-elasticsearch/blob/master/etc/river.toml#L3-L6

**Comment by zslsc18** [comment]
设置了，只是mysql服务器启动的时候，指定了socket的文件路径，我直接敲命令指定socket文件路径是可以dump的。 用户名，密码隐去
mysqldump -S /data/mysql/data/mysql.sock --databases tjk_db_v2  --tables tj_tjk_manage_role --result-file=/data/mysql/tj_tjk_manage_role.dump -uxxx -pxxx。我不会go语言，作者的代码中应该也是拼接mysqldump命令参数去执行的吧，作者可不可以在代码中加一个拼接socket文件路径的参数呢？

**Comment by EagleChen** [comment]
@zslsc18 

mysqldump 也可以通过 host 去执行的， 你试试把 `-S` 变成 `host` 和 `port`, 难道不能执行吗？
`host` 请设置成 `127.0.0.1` 不要用 `localhost`

`mysqldump --host xxxx --port xxxx --databases tjk_db_v2 --tables tj_tjk_manage_role --result-file=/data/mysql/tj_tjk_manage_role.dump -uxxx -pxxx`

**Comment by zslsc18** [comment]
@EagleChen  改成127.0.0.1可以了，谢谢。
