### ISSUE TITLE
更新索引失败后，数据同步停止，但是binlog postion仍然在变更

### ISSUE THREAD

**Issue by zslsc18** [siddontang/go-mysql-elasticsearch#189]
time="2017-11-29T19:00:01+08:00" level=error msg="update index: robot_customer_work_backend, type: robot_customer_work_backend, id: C20171129183954C0A8882700423309, status: 404, error: {\"type\":\"document_missing_exception\",\"reason\":
\"[robot_customer_work_backend][C20171129183954C0A8882700423309]: document missing\",\"index\":\"robot_customer_work_backend\",\"shard\":\"-1\"}"
time="2017-11-29T19:00:01+08:00" level=info msg="save position (bin-log.000945, 48978700)"
time="2017-11-29T19:00:04+08:00" level=info msg="save position (bin-log.000945, 49000339)"
time="2017-11-29T19:00:07+08:00" level=info msg="save position (bin-log.000945, 49345225)"
time="2017-11-29T19:00:10+08:00" level=info msg="save position (bin-log.000945, 49748208)"

**Comment by siddontang** [comment]
同步 binlog 是一个异步的行为，另外，为啥你的 index 没呢？自己删掉了吗

**Comment by zslsc18** [comment]
丢失的index应该是db insert的时候没有同步到es中，后面再执行update的时候，就报索引不存在了，没有手动删除过es中的数据，我把丢失的那几条数据手动添加到es中，然后重启同步程序就可以了。

**Comment by fly-studio** [comment]
```
2018/07/10 10:06:50 ERROR update index: xxxxxxxx, type: _doc, id: 25118810, status: 404, error: {"type":"document_missing_exception","reason":"[_doc][25118810]: document missing","index_uuid":"kIss_1YlRQasf3yfThnFiQ","shard":"4","index":"xxxxxxxx"}
```

我出现了同样的情况，index肯定是存在的，一直报这个错误，这个表（index） 有2千多万数据。

**Comment by solidossnakos** [comment]
Did you find a solution to this error?
I'm facing the same problem.

**Comment by jreio** [comment]
遇到了类似的问题，仔细的盘查了一下，我这边的问题是转移es旧数据时，数据未同步完，然后使用update做操作时，binglog涉及的数据未在es存在，程序就报 document_missing_exception，这是情况一，还有一种情况是在插入时遇到的也是同类问题

[2020/08/18 16:24:35] [error] sync.go:480 index index: test_member, type: _doc, id: 11992, status: 400, error: {"type":"mapper_parsing_exception","reason":"Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."}

目前还未分析出结果，感觉这个插件是不是对es7.3.x的支持力度是有限的？？
