### ISSUE TITLE
Do you have plans for supporting parent-children relationship in ES?

### ISSUE THREAD

**Issue by EagleChen** [siddontang/go-mysql-elasticsearch#19]
I've already add this function in [my fork](https://github.com/EagleChen/go-mysql-elasticsearch).
I can send a pull request if you want to add this.

**Comment by siddontang** [comment]
I see your fork and guess that if we create a table with column ID and its parent ID, and create the associated mapping in ES, we can support parent-children model, am I right?

Btw, does parent ID  need to support multi columns like ID?

**Comment by EagleChen** [comment]
@siddontang 
Yes. 

Currently, my implementation will pick up the value of a parent id field and use that as the id of the parent type in ES.
For example
```
blog table
id 1
title 't'
content 'c'

comment table
id 1
blog_id 1
content 'c'
```

Here, in the config, `blog_id` should be specified as parent id field. When syncing from mysql to ES, the value of `blog_id`, which is 1, will be used as the id of its parent.
I don't see the reason why parent id field need to be constructed with multi columns.

**Comment by siddontang** [comment]
greate, can you add an example in readme and then send the PR?

**Comment by EagleChen** [comment]
@siddontang 
OK. No problem.

**Comment by EagleChen** [comment]
pull request sent: https://github.com/siddontang/go-mysql-elasticsearch/pull/21
