### ISSUE TITLE
Not a valid win32 application.

### ISSUE THREAD

**Issue by wenkzz31** [siddontang/go-mysql-elasticsearch#191]
Im having a issue with canal it returns a not valid win32 application when dumping mysqldump. thank you

![image](https://user-images.githubusercontent.com/22561842/33559292-46d9957c-d947-11e7-8c09-e88161eb0705.png)

**Comment by siddontang** [comment]
seem you should use `mysqldump.exe` in your configuration.

**Comment by wenkzz31** [comment]
so im just going to change the .sql extension of my dump file to .exe? thank you for the response.
