### ISSUE TITLE
Connect to elasticsearch

### ISSUE THREAD

**Issue by wenkzz31** [siddontang/go-mysql-elasticsearch#192]
Elasticsearch 5.0 is running however there seems no connection initiated by the program to sync mysql with elasticsearch.

go-mysql-elasticsearch outputs
![image](https://user-images.githubusercontent.com/22561842/33644107-dd0914dc-da7d-11e7-8517-ca9dd751ff39.png)

Elasticsearch started
![image](https://user-images.githubusercontent.com/22561842/33644117-ee64f05c-da7d-11e7-824e-4f4a5411e79e.png)

Error when inserting data. My system runs 64 bit
![image](https://user-images.githubusercontent.com/22561842/33647997-c68367ac-da92-11e7-9a7d-38a821561bdc.png)

**Comment by siddontang** [comment]
the atomic problem may only be happened in the 32 bit system, can you ensure you build and run in the 64 bit?

**Comment by wenkzz31** [comment]
@siddontang yes im using gnumake 4.2.1 64 bit version for windows. still encountering atomic problem.

**Comment by siddontang** [comment]
asm386 means that you run a 32 bit platform, not 64. you can see https://github.com/golang/go/issues/6404

**Comment by wenkzz31** [comment]
@siddontang
