### ISSUE TITLE
关于SemiSyncEnabled

### ISSUE THREAD

**Issue by bohrqiu** [siddontang/go-mysql-elasticsearch#197]
hi，siddontang

我看了你的blog [Dive into MySQL Replication](http://siddontang.com/2015/03/28/dive-into-mysql-replication/)，里面提到支持半同步复制，但是我看[代码](https://github.com/siddontang/go-mysql-elasticsearch/blob/cb4e2b1d8005d4ed4458beb8b32ee360341440bd/vendor/github.com/siddontang/go-mysql/canal/canal.go#L395)并没有启用SemiSyncEnabled，这是为什么？

**Comment by siddontang** [comment]
对于 canal 来说默认不需要 semi-sync，如果你需要也可以自己去打开。

**Comment by bohrqiu** [comment]
canal不需要semi-sync，是因为默认是异步的么？

**Comment by siddontang** [comment]
主要是懒的加。。。
而且你也需要 MySQL 先打开 semi sync 支持

**Comment by bohrqiu** [comment]
^_^
