### ISSUE TITLE
Does anyone has this  Base64 Encoding problem?

### ISSUE THREAD

**Issue by lyz1990** [siddontang/go-mysql-elasticsearch#20]
I have a  filed of type "TEXT" in my  database table. After I insert "hello" in that filed, no matter through phpMyAdmin or PHP or command-line, it'll index  Base64 encoding as "aGVsbG8="  into EL document.
VARCHAR  just works fine, the problem is only with "TEXT" type.
![image](https://cloud.githubusercontent.com/assets/3955656/8903647/265eab3c-348c-11e5-970c-6c7645cb35c8.png)
If I delete the index, stop go-mysql-elasticsearch, and restart it to sync the database, it'll index "hello" this time and everything just works perfect. 
![image](https://cloud.githubusercontent.com/assets/3955656/8903694/698042e0-348c-11e5-980a-faf43cdf391e.png)

Does anyone has the same problem with me? Really need some directions.
By the way,  this project is awesome!!!  Thanks a lot.

**Comment by siddontang** [comment]
fix in https://github.com/siddontang/go-mysql-elasticsearch/pull/18 already.

**Comment by lyz1990** [comment]
Wow!!! Thanks a lot! Sorry that I haven't checked that first.
