### ISSUE TITLE
断线重连

### ISSUE THREAD

**Issue by itgeniusshuai** [siddontang/go-mysql-elasticsearch#202]
我想做个断线重连，就是每秒调用canal.binlogsyncer.conn.ping()判断连接是否有响应,为啥一直阻塞啊

**Comment by siddontang** [comment]
因为你不能用 conn 这个连接，而且现在内部已经支持断线重连

**Comment by itgeniusshuai** [comment]
我看之前的评论说不支持，才做的，既然支持了就不考虑了，能否还具体点为啥不能用conn这个连接

**Comment by siddontang** [comment]
因为这个连接会接受 binlog event，不能在给 mysql 发消息了

**Comment by itgeniusshuai** [comment]
恩，好的，谢谢，我再仔细看看您的代码，good luck
