### ISSUE TITLE
sync data from mysql to es "illegal_argument_exception" 400

### ISSUE THREAD

**Issue by mahone2080** [siddontang/go-mysql-elasticsearch#210]
status: 400, error: {"type":"illegal_argument_exception","reason":"Rejecting mapping update to [user] as the final mapping would have more than 1 type: [package, user]"}

so,what does this mean?

**Comment by EagleChen** [comment]
@mahone2080 

Elastcsearch 6.x does not support multiple types in one index.
You may need to use 5.x or older version.

**Comment by mahone2080** [comment]
![image](https://user-images.githubusercontent.com/6006761/35958855-f92d22e2-0cdd-11e8-9511-178210742d28.png)
the type name should also not be conflict with the other.
