### ISSUE TITLE
Save position aftering flush data?

### ISSUE THREAD

**Issue by monsterxx03** [siddontang/go-mysql-elasticsearch#220]
I'm writing a program to sync mysql binlog events to S3.

When looking river's code, seems flush logic and position save logic are split:  https://github.com/siddontang/go-mysql-elasticsearch/blob/master/river/sync.go#L149

After flushing data to es, position is not saved immediately, if river is killed or crashed, after it's restarted, last position will not be synced with data in es(or I missed something?).

I'm thinking save row events to a trxQueue temporarily. when receiving OnXiD event(transaction done), flush data in trxQueue to a bufferQueue, periodically dump data in bufferQueue to target (in my case S3), and save position immediately. 

Thanks for any suggestion.

**Comment by siddontang** [comment]
Hi @monsterxx03 

Because the position is synced later, so after the restart, we will resume syncing from last synced position, and we will sync some redundant data which has already been synced before.

**Comment by monsterxx03** [comment]
Thanks, I got it ~
