### ISSUE TITLE
when use  filter rule , wildcard can't be use?

### ISSUE THREAD

**Issue by dingding2015** [siddontang/go-mysql-elasticsearch#245]
I want to use it like this:
[[source]]
schema = "test"
tables = ["t_[0-9]*$"]

[[rule]]
schema = "test"
table = "t_[0-9]*$"
index = "test"
type = "doc"
filter = ["id", "name"]

but all the fields has beed synced.

**Comment by dingding2015** [comment]
I have know how to do it.

**Comment by kevinsir** [comment]
how to do that? i have the same problem
