### ISSUE TITLE
Amazon RDS问题

### ISSUE THREAD

**Issue by apprithm** [siddontang/go-mysql-elasticsearch#248]
我想amazon aurora里面的数据同步到es，但是发现aurora的账号缺少一些管理权限导致go-mysql-elasticsearch运行不了。请问有没有朋友试过在RDS用这个工具？是我没设置好，还是因为aws本身的权限导致不行？

谢谢

**Comment by siddontang** [comment]
maybe you can set `skip_master_data` to true, see https://github.com/siddontang/go-mysql-elasticsearch/blob/master/etc/river.toml#L36

**Comment by apprithm** [comment]
Thanks, that solved the problem.
