### ISSUE TITLE
int 类型 同步后变负数

### ISSUE THREAD

**Issue by vovolie** [siddontang/go-mysql-elasticsearch#259]
table 有个字段 int(11) 存的是数值化后的IP地址
dump时，在es内是正确的，replication 时，部份超出一定值后变成负数。

**Comment by vovolie** [comment]
+------------+--------------------------------------------+------+-----+---------+----------------+
| Field      | Type                                       | Null | Key | Default | Extra          |
+------------+--------------------------------------------+------+-----+---------+----------------+
| id         | int(11)                                    | NO   | PRI | NULL    | auto_increment |
| content    | text                                       | YES  |     | NULL    |                |
| article_id | int(11)                                    | NO   | MUL | NULL    |                |
| user_id    | int(11)                                    | NO   | MUL | 0       |                |
| created_at | datetime                                   | NO   |     | NULL    |                |
| status     | enum('publish','pending','private','spam') | NO   |     | pending |                |
| ip         | int(11) unsigned                           | NO   |     | 0       |                |
| anonymous  | tinyint(1)                                 | NO   |     | 0       |                |
| pos        | int(11)                                    | YES  |     | NULL    |                |
| neg        | int(11)                                    | YES  |     | NULL    |                |
| floor      | int(11)                                    | YES  |     | NULL    |                |
| score      | int(11)                                    | YES  |     | NULL    |                |
| parent_id  | int(11)                                    | YES  |     | NULL    |                |
| source     | varchar(255)                               | YES  |     | NULL    |                |
+------------+--------------------------------------------+------+-----+---------+----------------+

test data:
{u'status': 'publish', u'user_id': 123456, u'floor': 1610, u'ip': 3748168280, u'created_at': datetime.datetime(2018, 6, 4, 16, 33, 47), u'pos': None, u'content': 'x88', u'parent_id': 123456, u'score': 123456, u'source': 'android', u'anonymous': 0, u'neg': None, u'article_id': 123456, u'id': 123456}

elasticsearch result:
# ip |   | -547,754,993




# ip |   | -547,754,993
-- | -- | --

**Comment by vovolie** [comment]
I found the problem.
row_event.go func decodeValue() 
`
case MYSQL_TYPE_LONG:
		n = 4
		v = ParseBinaryInt32(data)
`
maybe need ParseBinaryInt64 ? or tp as longlogn？

**Comment by siddontang** [comment]
The problem is that we don't handle unsigned flag. 
For binlog, we can't know the number is unsigned or not, but for go-mysql-elasticsearch, we can know it, we need to convert to the unsigned value if we find the column is number and unsigned.

**Comment by vovolie** [comment]
Will you release fix version?

**Comment by siddontang** [comment]
no, have no time to fix it yet. maybe next week.

**Comment by vovolie** [comment]
coolest!

**Comment by vovolie** [comment]
has been fixed?

**Comment by siddontang** [comment]
no, too busy this week.

**Comment by siddontang** [comment]
@vovolie 

fixed
