### ISSUE TITLE
connection error message

### ISSUE THREAD

**Issue by apprithm** [siddontang/go-mysql-elasticsearch#267]
Hi,
 I'm having consistent connection error message, but the data is propagated to elastic search correctly. 
 Anyone has an idea why?

Here is the error message from the console:
2018/06/22 23:56:11 ERROR kill connection 17716 error ERROR 1094 (HY000): Unknown thread id: 17716
2018/06/22 23:56:11 INFO  kill last connection id 17716
2018/06/22 23:56:11 INFO  rotate to (mysql-bin-changelog.000013, 63856)
2018/06/22 23:56:11 INFO  receive EOF packet, retry ReadPacket
2018/06/22 23:56:11 ERROR  connection was bad
2018/06/22 23:56:11 INFO  rotate binlog to (mysql-bin-changelog.000013, 63856)
2018/06/22 23:56:11 INFO  save position (mysql-bin-changelog.000013, 63856)
2018/06/22 23:56:12 INFO  begin to re-sync from (mysql-bin-changelog.000013, 63856)
2018/06/22 23:56:12 INFO  register slave for master server ..........

**Comment by siddontang** [comment]
seem the connection to MySQL was broken and the syncer reconnected to the MySQL again, so your data can still be synced to ES.

**Comment by siddontang** [comment]
maybe you can increase your MySQL timeout configuration to relieve this problem.

**Comment by apprithm** [comment]
Im using Aurora MySQL. This message is continuously outputted **every second**. Do you still think it's a timeout issue?

**Comment by siddontang** [comment]
Aurora? We haven't tested it on Aurora.

Do you explicitly enable semi-sync replication? if yes, you need to set SemiSyncEnabled to true.

**Comment by apprithm** [comment]
yeah, AWS Aurora. I'm using mysql 5.7 compatible version.
I looked into the parameter group settings, there is no setting related to semi-sync that I can modify.
I also changed connect_timeout to a longer value. That didn't help neither.

Based on the error log, it looks like the go-mysql-elasticsearch app it is trying to kill the connection, but it failed due to can no longer find that thread id.

**Comment by apprithm** [comment]
Here is a snapshot of the fresh log. I deleted master.info and started the syncer, if you look at the timestamp, it reports the error every second:

2018/06/25 22:51:01 INFO  run status http server 127.0.0.1:12800
2018/06/25 22:51:01 INFO  skip master data, get current binlog position (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:01 INFO  try dump MySQL and parse
mysqldump: [Warning] Using a password on the command line interface can be insecure.
2018/06/25 22:51:01 INFO  dump MySQL and parse OK, use 0.13 seconds, start binlog replication at (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:01 INFO  begin to sync binlog from position (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:01 INFO  register slave for master server wiz-database-prod-cluster.cluster-ro-cfqo6cjytuk4.us-west-1.rds.amazonaws.com:5378
2018/06/25 22:51:01 INFO  start sync binlog at binlog file (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:01 INFO  rotate to (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:01 INFO  receive EOF packet, retry ReadPacket
2018/06/25 22:51:01 ERROR  connection was bad
2018/06/25 22:51:01 INFO  rotate binlog to (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:01 INFO  save position (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:02 INFO  begin to re-sync from (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:02 INFO  register slave for master server wiz-database-prod-cluster.cluster-ro-cfqo6cjytuk4.us-west-1.rds.amazonaws.com:5378
2018/06/25 22:51:02 ERROR kill connection 550 error ERROR 1094 (HY000): Unknown thread id: 550
2018/06/25 22:51:02 INFO  kill last connection id 550
2018/06/25 22:51:02 INFO  rotate to (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:02 INFO  receive EOF packet, retry ReadPacket
2018/06/25 22:51:02 ERROR  connection was bad
2018/06/25 22:51:02 INFO  rotate binlog to (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:02 INFO  save position (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:03 INFO  begin to re-sync from (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:03 INFO  register slave for master server wiz-database-prod-cluster.cluster-ro-cfqo6cjytuk4.us-west-1.rds.amazonaws.com:5378
2018/06/25 22:51:03 ERROR kill connection 552 error ERROR 1094 (HY000): Unknown thread id: 552
2018/06/25 22:51:03 INFO  kill last connection id 552
2018/06/25 22:51:03 INFO  rotate to (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:03 INFO  receive EOF packet, retry ReadPacket
2018/06/25 22:51:03 ERROR  connection was bad
2018/06/25 22:51:03 INFO  rotate binlog to (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:03 INFO  save position (mysql-bin-changelog.000015, 22590)
^C2018/06/25 22:51:04 INFO  receive signal interrupt, closing
2018/06/25 22:51:04 INFO  closing river
2018/06/25 22:51:04 INFO  closing canal
2018/06/25 22:51:04 INFO  syncer is closing...
2018/06/25 22:51:04 ERROR close sync with err: Sync was closed
2018/06/25 22:51:04 INFO  syncer is closed
2018/06/25 22:51:04 INFO  save position (mysql-bin-changelog.000015, 22590)
2018/06/25 22:51:04 ERROR canal start sync binlog err: Sync was closed
2018/06/25 22:51:04 ERROR start canal err Sync was closed

**Comment by siddontang** [comment]
The root cause is 
```
2018/06/25 22:51:02 INFO receive EOF packet, retry ReadPacket
2018/06/25 22:51:02 ERROR connection was bad
```

The log means that syncer receives an EOF package, not valid data or OK Packet, so it has to close the connection. 

I have two assumptions:

1. Aurora enable semi-sync, What is output with `show variables like '%semi%';`
2. Aurora provides another replication protocol which is different from official 5.7, for this, have you tested it with AWS RDS or official 5.7?

**Comment by apprithm** [comment]
Nothing show up in the result after executing **show variables like '%semi%';**
I haven't tested it with AWS RDS.

**Comment by apprithm** [comment]
I will setup a RDS and if the problem happens and report back.

**Comment by apprithm** [comment]
I tried RDS mysql5.7, same error. Please see the log below:
```
2018/06/29 22:12:53 INFO  create BinlogSyncer with config {0 mysql testdb-test.flkjvoiweo3.us-west-1.rds.amazonaws.com 3306 unicorn   utf8 false false <nil> false false 0 0s 0s 0}
2018/06/29 22:12:53 INFO  run status http server 127.0.0.1:12800
2018/06/29 22:12:53 INFO  skip master data, get current binlog position (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:53 INFO  try dump MySQL and parse
mysqldump: [Warning] Using a password on the command line interface can be insecure.
2018/06/29 22:12:54 INFO  dump MySQL and parse OK, use 0.05 seconds, start binlog replication at (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:54 INFO  begin to sync binlog from position (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:54 INFO  register slave for master server testdb-test.flkjvoiweo3.us-west-1.rds.amazonaws.com:3306
2018/06/29 22:12:54 INFO  start sync binlog at binlog file (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:54 INFO  rotate to (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:54 INFO  receive EOF packet, retry ReadPacket
2018/06/29 22:12:54 ERROR  connection was bad
2018/06/29 22:12:54 INFO  rotate binlog to (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:54 INFO  save position (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:55 INFO  begin to re-sync from (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:55 INFO  register slave for master server testdb-test.flkjvoiweo3.us-west-1.rds.amazonaws.com:3306
2018/06/29 22:12:55 ERROR kill connection 12 error ERROR 1094 (HY000): Unknown thread id: 12
2018/06/29 22:12:55 INFO  kill last connection id 12
2018/06/29 22:12:55 INFO  rotate to (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:55 INFO  receive EOF packet, retry ReadPacket
2018/06/29 22:12:55 ERROR  connection was bad
2018/06/29 22:12:55 INFO  rotate binlog to (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:55 INFO  save position (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:56 INFO  begin to re-sync from (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:56 INFO  register slave for master server testdb-test.flkjvoiweo3.us-west-1.rds.amazonaws.com:3306
2018/06/29 22:12:56 ERROR kill connection 13 error ERROR 1094 (HY000): Unknown thread id: 13
2018/06/29 22:12:56 INFO  kill last connection id 13
2018/06/29 22:12:56 INFO  rotate to (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:56 INFO  receive EOF packet, retry ReadPacket
2018/06/29 22:12:56 ERROR  connection was bad
2018/06/29 22:12:56 INFO  rotate binlog to (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:56 INFO  save position (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:57 INFO  begin to re-sync from (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:57 INFO  register slave for master server testdb-test.flkjvoiweo3.us-west-1.rds.amazonaws.com:3306
2018/06/29 22:12:57 ERROR kill connection 14 error ERROR 1094 (HY000): Unknown thread id: 14
2018/06/29 22:12:57 INFO  kill last connection id 14
2018/06/29 22:12:57 INFO  rotate to (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:57 INFO  receive EOF packet, retry ReadPacket
2018/06/29 22:12:57 ERROR  connection was bad
2018/06/29 22:12:57 INFO  rotate binlog to (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:57 INFO  save position (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:58 INFO  begin to re-sync from (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:58 INFO  register slave for master server testdb-test.flkjvoiweo3.us-west-1.rds.amazonaws.com:3306
2018/06/29 22:12:58 ERROR kill connection 15 error ERROR 1094 (HY000): Unknown thread id: 15
2018/06/29 22:12:58 INFO  kill last connection id 15
2018/06/29 22:12:58 INFO  rotate to (mysql-bin-changelog.000046, 511)
2018/06/29 22:12:58 INFO  receive EOF packet, retry ReadPacket
2018/06/29 22:12:58 ERROR  connection was bad
```

**Comment by july2993** [comment]
i just set up a RDS instance to test, but work fine for me
```
➜  go-mysql-elasticsearch git:(master) ✗ ./bin/go-mysql-elasticsearch ./etc/river.toml
2018/07/01 16:46:25 INFO  create BinlogSyncer with config {1001 mysql mytest.cyoymdacr5is.us-east-2.rds.amazonaws.com 3306 mytest   utf8 false false <nil> false false 0 0s 0s 0}
2018/07/01 16:46:27 INFO  run status http server 127.0.0.1:12800
2018/07/01 16:46:27 INFO  skip master data, get current binlog position (mysql-bin-changelog.000026, 154)
2018/07/01 16:46:27 INFO  try dump MySQL and parse
mysqldump: [Warning] Using a password on the command line interface can be insecure.
2018/07/01 16:46:35 INFO  dump MySQL and parse OK, use 7.57 seconds, start binlog replication at (mysql-bin-changelog.000026, 154)
2018/07/01 16:46:35 INFO  begin to sync binlog from position (mysql-bin-changelog.000026, 154)
2018/07/01 16:46:35 INFO  register slave for master server mytest.cyoymdacr5is.us-east-2.rds.amazonaws.com:3306
2018/07/01 16:46:36 INFO  start sync binlog at binlog file (mysql-bin-changelog.000026, 154)
2018/07/01 16:46:37 INFO  rotate to (mysql-bin-changelog.000026, 154)
2018/07/01 16:46:37 INFO  rotate binlog to (mysql-bin-changelog.000026, 154)
2018/07/01 16:46:37 INFO  save position (mysql-bin-changelog.000026, 154)
2018/07/01 16:47:17 INFO  save position (mysql-bin-changelog.000026, 511)
2018/07/01 16:47:24 INFO  save position (mysql-bin-changelog.000026, 766)
2018/07/01 16:47:28 INFO  save position (mysql-bin-changelog.000026, 1021)
2018/07/01 16:47:49 INFO  save position (mysql-bin-changelog.000026, 1276)
```

**Comment by siddontang** [comment]
@july2993 do you use RDS 5.7? how about Aurora?

**Comment by july2993** [comment]
> @july2993 do you use RDS 5.7? how about Aurora?

yes,  not having test Aurora myself yet, but according to what i know, some guy had tested it before and work fine.
looks like the same problem according to the log of @apprithm using RDS or Aurora

**Comment by july2993** [comment]
@apprithm 
same configuration change with you.
i simply create a table by "create table test(id int, primary key(id))"
and keep insert data to it, it look good.
can you show me what data you load to mysql? so i can try weather i can reproduce the problem

**Comment by siddontang** [comment]
@apprithm 

Do you use the latest version? what is the server ID do you use?

**Comment by apprithm** [comment]
@siddontang 
I just tried the latest version from the repo today. Same problem.
I'm using serverid: 1001 and serverid: 1

**Comment by siddontang** [comment]
@apprithm 

What is your account? does it have the privilege of replication? Or any firewall? can you use tcpdump to capture the data?

This is a very strange bug, we can't reproduce it with RDS. @july2993

**Comment by apprithm** [comment]
I'm using same username thats being generated when I created the mysql database in AWS RDS. I believe it has the highest privilege thats available.
There is no special firewall between the EC2 instance hosting go-mysql0elasticsearch and the RDS instance. It's in the same region and same VPC, there is no special rules.

**Comment by siddontang** [comment]
can you give me the way to login to your server? then I can check why this happens. My email is siddontang@gmail.com

**Comment by apprithm** [comment]
@siddontang Have you received my email ?

**Comment by siddontang** [comment]
hi @apprithm 

seem that I have found the problem, your server id name is wrong
```
# pseudo server id like a slave
serve_id = 1
```

serve_id should be server_id

**Comment by apprithm** [comment]
@siddontang 
Thank you very much ! The problem was indeed caused by the typo 👍 
I'm closing the issue now.
