### ISSUE TITLE
cannot sync data

### ISSUE THREAD

**Issue by EagleChen** [siddontang/go-mysql-elasticsearch#27]
I don't know what configuration is wrong.
mysqldump is OK.
But sync does not work.

Could you help me to figure out why?
Here are some logs:

```
dump.go:113 [Info] dump MySQL and parse OK, use 704.79 seconds, start binlog replication at (mariadb-bin.000001, 1478069)
sync.go:15 [Info] start sync binlog at (mariadb-bin.000001, 1478069)
canal.go:146 [Error] canal start sync binlog err: connection was bad
```

**Comment by siddontang** [comment]
Hi @EagleChen 

This seems that the connection was broken, but I don't know why here, and need more information.

In my another go-mysql which go-mysql-elasticsearch depends on, you can use make to build a go-mysqlbinlog command tool in ./bin folder, and it can test whether you can sync with MySQL or not, maybe :-) 

e.g. `./bin/go-mysqlbinlog --host=127.0.0.1 --port=3306 --use=root --password=pass --flavor=mariadb --file-mariadb-bin.000001 --pos=1478069 `

**Comment by EagleChen** [comment]
@siddontang 

if the connection is broken, then why can "mysqldump" work?
I'll try your method.

**Comment by EagleChen** [comment]
@siddontang 

Yes. You method can work.
I see output like the following:
```
=== UpdateRowsEventV1 ===
Date: 2015-09-19 08:07:04
Log position: 1297768
Event size: 496
TableID: 889
Flags: 1
Column count: 10
Values:
```

**Comment by siddontang** [comment]
mysqldump use official mysqldump tool, it uses another connection, not the same for sync. 

Do you set the config correctly, especially here
```
# mysql or mariadb
flavor = "mysql"
```
I guess you use mariadb, not mysql. 

Or can you show me your configuration?

**Comment by EagleChen** [comment]
```
my_addr = "172.17.0.10:3306"
my_user = "user"
my_pass = "pass"
es_addr = "172.17.0.1:9200"
data_dir = "/data"
stat_addr = "0.0.0.0:12800"
server_id = 1001
flavor = "mariadb"
mysqldump = "/usr/bin/mysqldump"
```

then remaining config includes [[source]], [[rule]]

**Comment by EagleChen** [comment]
I restarted the docker container which contains the river. And then everything works.

**Comment by siddontang** [comment]
:sweat:
