### ISSUE TITLE
/usr/bin/mysqldump: unknown variable 'set-gtid-purged=OFF'

### ISSUE THREAD

**Issue by lloiacono** [siddontang/go-mysql-elasticsearch#278]
I get this when I try to run

`./bin/go-mysql-elasticsearch -config=etc/river.toml`

I double checked my configuration in river.toml and also made sure that mysqldump is accessible. 

Full output:

> 2018/07/17 14:47:49 INFO  create BinlogSyncer with config {1001 percona mydb 3306 my_user   utf8 false false <nil> false false 0 0s 0s 0}
2018/07/17 14:47:49 INFO  try dump MySQL and parse
2018/07/17 14:47:49 INFO  run status http server 127.0.0.1:12800
/usr/bin/mysqldump: unknown variable 'set-gtid-purged=OFF'
2018/07/17 14:47:49 ERROR canal dump mysql err: exit status 7
2018/07/17 14:47:49 ERROR start canal err exit status 7

**Comment by siddontang** [comment]
interesting, which version do you use? seem we have no place to pass "set-gtid-purged" now.

**Comment by lloiacono** [comment]
I am using the official docker image from here: https://hub.docker.com/_/golang/
I installed mysql-client like this:

`apt-get update && apt-get install mysql-client`

My DB is Percona Server: 5.7.21-20

**Comment by siddontang** [comment]
can you use the binary to reproduce it? seem the docker is out of date?

**Comment by lloiacono** [comment]
Fixed it after manually installing mysql-client 5.7
