### ISSUE TITLE
Makefile issue 

### ISSUE THREAD

**Issue by Faizanq** [siddontang/go-mysql-elasticsearch#282]
go build -o bin/go-mysql-elasticsearch ./cmd/go-mysql-elasticsearch
river/river.go:4:2: cannot find package "context" in any of:
	/home/qureshi/go_work/src/github.com/siddontang/go-mysql-elasticsearch/vendor/context (vendor tree)
	/usr/local/go/src/context (from $GOROOT)
	/home/qureshi/go_work/src/context (from $GOPATH)
Makefile:6: recipe for target 'build-elasticsearch' failed
make: *** [build-elasticsearch] Error 1

**Comment by siddontang** [comment]
oh, interesting, what is your go version?

**Comment by Faizanq** [comment]
I think this is not related to version, maybe makefile not find a path

**Comment by siddontang** [comment]
please use 1.9+

I am surprised that you have still used such an old version.

**Comment by Faizanq** [comment]
Yes I have done with new version thanks
