### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by andreaboccaforno** [siddontang/go-mysql-elasticsearch#286]
Hello,
i have installed this extension, but doesn't work.

these are the logs:

 [info] binlogsyncer.go:111 create BinlogSyncer with config {1001 mysql 127.0.0.1 3306 abcerca   utf8 false false <nil> false false 0 0s 0s 0}
github.com/siddontang/go-mysql/canal/canal.go:392: binlog must ROW format, but STATEMENT now
github.com/siddontang/go-mysql/canal/canal.go:83: 
/root/go/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:108: 
/root/go/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:58: 

no synchronization is performed, what can it be?

**Comment by siddontang** [comment]
> binlog must ROW format, but STATEMENT now

Please use ROW format.

**Comment by andreaboccaforno** [comment]
How can i do it?

**Comment by andreaboccaforno** [comment]
I have done it, now the logs are:

[info] binlogsyncer.go:111 create BinlogSyncer with config {1001 mysql 127.0.0.1 3306 abcerca   utf8 false false <nil> false false 0 0s 0s 0}
/root/go/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:216: no source data defined
/root/go/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:225: 
/root/go/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:62:

**Comment by andreaboccaforno** [comment]
How can i add privelige?

Thank you

**Comment by siddontang** [comment]
please google `MySQL replication privilege`

**Comment by andreaboccaforno** [comment]
thank you, i have set replication privilege, but now i have this log:

[2018/08/12 13:58:33] [error] binlogstreamer.go:57 close sync with err: ERROR 1236 (HY000): Binary log is not open
[2018/08/12 13:58:33] [error] canal.go:216 canal start sync binlog err: ERROR 1236 (HY000): Binary log is not open
[2018/08/12 13:58:33] [error] river.go:299 start canal err ERROR 1236 (HY000): Binary log is not open

Thank you.

**Comment by andreaboccaforno** [comment]
it seems that everything works, the only problem is when I close the console, as it ends the synchronization, how can I leave it always active?

**Comment by siddontang** [comment]
Please google nohup, like 

https://www.cyberciti.biz/tips/nohup-execute-commands-after-you-exit-from-a-shell-prompt.html

This is not related to this project anymore, I will close it now.
