### ISSUE TITLE
How to add a new table without dump old tables?

### ISSUE THREAD

**Issue by xuxiaomo** [siddontang/go-mysql-elasticsearch#289]
### Short description
I want to add a new table, but don't dump old tables

### Example
1. The initial configuration is as follows
```
[[source]]
schema = "testdb"
tables = ["testtable"]
```
2. Then I want add a new table
```
[[source]]
schema = "testdb"
tables = ["testtable","newtable"]
```
3. The data for the new table will not be synchronized

### Temporary solution
I have to delete master.info file and dump all tables again. It's too expensive, Is there a better solution?

**Comment by siddontang** [comment]
oh, I have not considered this usage before.

Maybe now the only better way is to start another go-mysql-eleasticsearch :-)

**Comment by xuxiaomo** [comment]
Hi, I found the previous test to be wrong. Simply restart the service and the new tables can be synchronized.

### Example
1. The configuration is as follows
```
[[source]]
schema = "testdb"
tables = ["*"]
```
2. Create a table
```
CREATE TABLE `testdb`.`newtable` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`));
```
3. Insert data
```
INSERT INTO `testdb`.`newtable` (`id`) VALUES ('1');
```
4. This data will not be synchronized
```
ES Query:
GET /newtable/_search
{
  "query": {"match_all": {}}
} 

ES Result:
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "newtable",
        "index_uuid": "_na_",
        "index": "newtable"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_or_alias",
    "resource.id": "newtable",
    "index_uuid": "_na_",
    "index": "newtable"
  },
  "status": 404
}
```
5. Then restart serivce and insert data
```
INSERT INTO `testdb`.`newtable` (`id`) VALUES ('2');
```
6. Id 2 is synchronized, but id1 is lost
```
ES Query:
GET /newtable/_search
{
  "query": {"match_all": {}}
} 

ES Result:
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "newtable",
        "_type": "newtable",
        "_id": "2",
        "_score": 1,
        "_source": {
          "id": 2
        }
      }
    ]
  }
}
```

This behavior is confusing. what‘s’ happened?

**Comment by siddontang** [comment]
For `*`, we will select all tables from MySQL and use it. So it can't know your new table because all the table rules have been created at first.

So after the restart, the new table will be synced.

**Comment by xuxiaomo** [comment]
OK, It's work.  :)
But it's not elegant, That's a pity.
