### ISSUE TITLE
Using it with docker

### ISSUE THREAD

**Issue by apprithm** [siddontang/go-mysql-elasticsearch#299]
Hi tang,

 Im trying to use it with docker and ship the river file in the image.

 When I make a change in the river file, I need to generate a new image and deploy it to the server. I assume that will cause the /var/master.info in the previous container will be reinitialized right ? And then duplicate data will dump in to elastic search.
 Whats the best practice for handling this issue? Can I have the master.info seats outside of the container( like S3)?

Please correct me if Im wrong :)

**Comment by siddontang** [comment]
Hello @apprithm 

I haven't used it in docker. maybe we can mount the var outside docker so every docker can use it?

**Comment by apprithm** [comment]
@apprithm Yes, If we have the control of the host machine, that will be a solution. But Im thinking about deploying it to beanstalk for now.

**Comment by siddontang** [comment]
@apprithm another solution may saving to the remote storage, like etcd, like https://github.com/siddontang/go-mysql-elasticsearch/pull/253

**Comment by siddontang** [comment]
but this PR has not been updated for a long time, can you improve it?

**Comment by apprithm** [comment]
I will take a look. Thanks for pointing it out !
