### ISSUE TITLE
不支持单表索引多个不同type吗？

### ISSUE THREAD

**Issue by bbszt** [siddontang/go-mysql-elasticsearch#34]
单表所属多个父表，es好像不支持多parent，想将一表索引成不同type，然后分别指定各parent。但同步时好像无法将数据同步至各个不同type中，只在最后一个type里有数据。

**Comment by siddontang** [comment]
当初设计的时候就是只支持table -> type这种映射的。如果真有这样的需要，欢迎提PR，主要是我现在没用ES，所以这边只会优先考虑bugfix，额外的feature可能只会todo了。

**Comment by bbszt** [comment]
兄弟啊，go我以前还会点语法，现在忘的看都看不懂了。有心无力
