### ISSUE TITLE
go test failed with parent test

### ISSUE THREAD

**Issue by siddontang** [siddontang/go-mysql-elasticsearch#35]
Hi @EagleChen 

run go test failed with parent test:

```
FAIL: river_extra_test.go:92: riverTestSuite.TestRiverWithParent

river_extra_test.go:103:
    s.testElasticExtraExists(c, "1", "1", true)
river_extra_test.go:86:
    c.Assert(r.Code, Equals, http.StatusOK)
... obtained int = 404
... expected int = 200
```

I use siddontang/mysql and newest elasticsearch:latest docker to test. 
Can you help me find why failed? Thank you.

**Comment by cool14521** [comment]
me too

**Comment by EagleChen** [comment]
@siddontang 

ElasticSearch 2 makes more limitations on "child-parent" relationship.
Can you please verify whether this [pull request](https://github.com/siddontang/go-mysql-elasticsearch/pull/37) can fix the test ?

**Comment by siddontang** [comment]
Yes, fix.
But what is the limitation for this relationship?

**Comment by EagleChen** [comment]
@siddontang 

In previous version, I can set the same type for "child" and "parent".
But for ES 2, I cannot do that anymore.
This fix just creates another type as "parent".

**Comment by siddontang** [comment]
Got it
