### ISSUE TITLE
How can I set the analyzer of a field

### ISSUE THREAD

**Issue by blackconcerto** [siddontang/go-mysql-elasticsearch#42]
In elasticsearch-jdbc:
type_mapping: {
      "blog": {
        dynamic: true, 
        properties: {
		  "title" : { "type" : "string", "analyzer" : "ik_analyzer", "search_analyzer" : "ik_analyzer" }, 
		  "content" : { "type" : "string", "analyzer" : "ik_analyzer", "search_analyzer" : "ik_analyzer" }
        }
      }
    },

Do go-mysql-elasticesearch support any way to set the properties of a field, besides the elasticsearch type?

**Comment by siddontang** [comment]
Hi @blackconcerto 

Can you give me a simple example? I don't know what you mean, sorry.

**Comment by blackconcerto** [comment]
@siddontang ,Oh, sorry, I will explain my problem.
When sync the data from mysql to elasticsearch, we need to set the  the associated mappings in Elasticsearch. To define the field type, I find the Rule field types in go-mysql-elasticesearch can be uesed. 

[[rule]]
schema = "test"
table = "t1"
index = "t"
type = "t"
parent = "parent_id"

    [rule.field]
    // This will map column title to elastic search my_title
    title="my_title"


However, i also need to define fomatter and analyzer of a field in the mapping.
{
    "tweet": {
        "type":     "string",
        "analyzer": "english"
    }
}
Just like [elasticsearch guide](https://github.com/elastic/elasticsearch-definitive-guide/blob/master/052_Mapping_Analysis/45_Mapping.asciidoc)

So I wonder if go-mysql-elasticesearch can sopport it?

**Comment by siddontang** [comment]
Hi @blackconcerto 
I think you should define these in the ES mapping, not here. If I remember correctly, ES doesn't support changing mapping dynamically easily, so you should design and write your own mapping in ES first. 

go-mysql-elasticsearch doesn't support this, and it only syncs mysql data to ES with corresponding field.
But I don't know now whether ES can support using another analyzer when we syncing data, E,g, we can explicitly let ES using another analyzer instead of defined in mapping.

**Comment by blackconcerto** [comment]
Hi @siddontang , thanks for your answer. 
Yeah, I work it out by defining the mapping and index properties before sync just now. I was afraid that the synchronization will rebuid a new index, or change the index setting. But the ES doesn't allow to change mapping, and go-mysql-elasticsearch will not change the setting, too. It's great!

**Comment by luantranminh** [comment]
Hi @blackconcerto, Could you share your config file?
I define the mapping and index properties first. But, when my old data get dumped, go-mysql-elasticsearch said I've redefining some index.
```
error: {"type":"illegal_argument_exception","reason":"Rejecting mapping update to [city] as the final mapping would have more than 1 type: [_doc, cityc]"}
```

**Comment by imom0** [comment]
the same problem
