### ISSUE TITLE
Getting error when restart sync

### ISSUE THREAD

**Issue by blackconcerto** [siddontang/go-mysql-elasticsearch#43]
Hello,I got the log bellow:
```
[2016/06/17 15:25:15] sync.go:15 [Info] start sync binlog at (mysql-bin.000001, 4969960)
[2016/06/17 15:25:15] status.go:52 [Info] run status http server 127.0.0.1:12800[2016/06/17 15:25:15] sync.go:46 [Info] rotate binlog to (mysql-bin.000001, 4969960)
[2016/06/17 15:25:15] sync.go:50 [Error] handle rows event error ERROR 1146 (42S02): Table 'test.geo' doesn't exist
[2016/06/17 15:25:15] canal.go:146 [Error] canal start sync binlog err: ERROR 1146 (42S02): Table 'test.geo' doesn't exist
```

I have synchronize my data before, and the index is on a table of a database. Then I insert some data into another table and drop the table after shutdown the sync program. And when I restart the sync program, it got the error. The program found the dump data, and just run according to the binlog. However, the binlog is recorded in order, and the drop record is after the insert record. It causes the problem and the program stopped. The record after the dropping record can't be synchronized.

**I think it is important that the synchronization could not be affected by the operations of other table**.

At last, I need to delete the dump data before, dump the data, and restart go-mysql-elasticsearch. It worked well.

**Comment by siddontang** [comment]
Hi @blackconcerto 

I know this problem, even more, if you alter your table dynamically, it may still fail too. 

I have no way to fix it now, for dropped table, we may ignore this syncing data, but for altered table, we can't know the differences easily (you may even change ES mapping too), so I write `Can not alter table format at runtime.` in readme.

**Comment by blackconcerto** [comment]
Hi, @siddontang .
I will try to add some strategies to ignore the records of other table, when the sync  is operated on designated tables. I'm expecting the problem to be solved.
