### ISSUE TITLE
 binlog must ROW format, but STATEMENT now

### ISSUE THREAD

**Issue by qsbaq** [siddontang/go-mysql-elasticsearch#53]
github.com/siddontang/go-mysql/canal/canal.go:242: binlog must ROW format, but STATEMENT now
github.com/siddontang/go-mysql/canal/canal.go:84: 
/root/.go/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:82: 
/root/.go/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:44: 

配置文件如下：

`[root@iZ22vmzhajwZ go-mysql-elasticsearch]# vi etc/river.toml 

# MySQL address, user and password
# user must have replication privilege in MySQL.
my_addr = "127.0.0.1:3306"
my_user = "root"
my_pass = "jjjjjj"

# Elasticsearch address
es_addr = "10.25.166.191:9200"

# Path to store data, like master.info, and dump MySQL data
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# MySQL data source
[[source]]
schema = "torrent"

# Only below tables will be synced into Elasticsearch.
# "test_river_[0-9]{4}" is a wildcard table format, you can use it if you have many sub tables, like table_0000 - table_1023
# I don't think it is necessary to sync all tables in a database.
tables = ["torrent[0-9]{1}"]

# Below is for special rule mapping
[[rule]]
schema = "torrent"
table = "torrent[0-9]{1}"
index = "torrent"`

**Comment by siddontang** [comment]
any problem? 
should set to row for work.

**Comment by qsbaq** [comment]
How to set row ？
Can u speek Chinese ？

发自我的 iPhone

**Comment by siddontang** [comment]
see http://dev.mysql.com/doc/refman/5.7/en/binary-log-setting.html
