### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by itarafath** [siddontang/go-mysql-elasticsearch#59]
I'm  new to ES and GO. What does **make** command do? It does not work.

**Comment by siddontang** [comment]
what's the error?

**Comment by itarafath** [comment]
![image](https://cloud.githubusercontent.com/assets/1159869/19833950/43c7bbae-9e09-11e6-87e0-2a3fc7e5648e.png)

**Comment by siddontang** [comment]
Seem that you must install `make`. Or you can use `go build -o bin/go-mysql-elasticsearch ./cmd/go-mysql-elasticsearch` directly to install go-mysql-elasticsearch.

**Comment by itarafath** [comment]
![image](https://cloud.githubusercontent.com/assets/1159869/19838193/6e6edc4c-9e87-11e6-868e-3026f24f8c9a.png)
i got this error.

**Comment by siddontang** [comment]
`./bin/go-msyql-elasticsearch` not `bin\go-mysql-elasticsearch`

**Comment by itarafath** [comment]
Yes. I tried that too. Doesn't work.

**Comment by itarafath** [comment]
Is there anyone

**Comment by siddontang** [comment]
You can enter the go-mysql-elasticsearch bin path to see whether the binary exists or not.

**Comment by itarafath** [comment]
@siddontang Nothing happened.

**Comment by siddontang** [comment]
What does `go build -o ./bin/go-mysql-elasticsearch ./cmd/go-mysql-elasticsearch` output? 
Can you show me the file list in ./bin directory?

**Comment by itarafath** [comment]
after compile
![image](https://cloud.githubusercontent.com/assets/1159869/19933991/74e519ae-a0d2-11e6-94eb-98efdb23fffd.png)

There is only one file.
![image](https://cloud.githubusercontent.com/assets/1159869/19933792/d768628a-a0d1-11e6-8a1e-0752749e8923.png)

**Comment by siddontang** [comment]
try `go build -o ./bin/go-mysql-elasticsearch.exe ./cmd/go-mysql-elasticsearch`

Seem that windows can't run `go-mysql-elasticsearch` directly.

**Comment by itarafath** [comment]
@siddontang it works. Thank you
