### ISSUE TITLE
No data synced

### ISSUE THREAD

**Issue by itarafath** [siddontang/go-mysql-elasticsearch#61]
the programme works perfectly. But there is no data synced. below I attached the screenshot.
![image](https://cloud.githubusercontent.com/assets/1159869/19979869/3bcc5942-a1b9-11e6-84d8-aeefaa8fb147.png)

I am using XAMPP. This is my rivor.toml configuration.
`# MySQL address, user and password
# user must have replication privilege in MySQL.
my_addr = "127.0.0.1:3306"
my_user = "root"
my_pass = ""

# Elasticsearch address
es_addr = "127.0.0.1:9200"

# Path to store data, like master.info, and dump MySQL data
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# MySQL data source
[[source]]
schema = "test"

# Only below tables will be synced into Elasticsearch.
# "test_river_[0-9]{4}" is a wildcard table format, you can use it if you have many sub tables, like table_0000 - table_1023
# I don't think it is necessary to sync all tables in a database.
#tables = ["test_river", "test_river_[0-9]{4}"]
tables = ["a"]

# Below is for special rule mapping
[[rule]]
schema = "test"
table = "a"
index = "users"
type = "user"

    # title is MySQL test_river field name, es_title is the customized name in Elasticsearch
    [rule.field]
    # This will map column title to elastic search my_title
    title="es_title"
    # This will map column tags to elastic search my_tags and use array type
    tags="my_tags,list"
    # This will map column keywords to elastic search keywords and use array type
    keywords=",list"

# wildcard table rule, the wildcard table must be in source tables
# [[rule]]
# schema = "test"
# table = "test_river_[0-9]{4}"
# index = "river"
# type = "river"

    # title is MySQL test_river field name, es_title is the customized name in Elasticsearch
    # [[rule.fields]]
    # mysql = "title"
    # elastic = "es_title"

#table name change to `a`
`

**Comment by siddontang** [comment]
Hi @itarafath 

Do you have a `users` table in `test` database?

**Comment by itarafath** [comment]
Yes..available.

**Comment by siddontang** [comment]
can you insert some data and then flush logs, the mysql binlog will be rotated and go-mysql-elasticsearch will log this.

**Comment by itarafath** [comment]
Thanks . It works . But sync only newly inserted data, existing data are missing.

**Comment by siddontang** [comment]
can you use `select * from users` to see the existing data which are not synced?

**Comment by itarafath** [comment]
it won't work.

**Comment by siddontang** [comment]
seem that you don't install mysqldump, so go-mysql-elesticsearch can't sync the data which does not exist in binlog. 

mysqldump is contained in MySQL, maybe you can install it? Sorry that I have no Windows computer so I don't know how to do it.

**Comment by itarafath** [comment]
MySQL dump is working fine. Is there any specific path for MySQL dump file.
Which folder should contain MySQL dump file.

**Comment by siddontang** [comment]
We don't save dump file, just dump the data from MySQL and sync to ES with a Pipe.

**Comment by itarafath** [comment]
If I run `mysqldump dbName` its working. Then what should be wrong?

**Comment by siddontang** [comment]
Delete the data directory set in `data_dir` configuration and restart the again. Hope this can solve your problem.

**Comment by itarafath** [comment]
No :( . Not worked.

**Comment by siddontang** [comment]
Can you show me the console output?

**Comment by itarafath** [comment]
![image](https://cloud.githubusercontent.com/assets/1159869/20036885/15901f64-a43b-11e6-8b22-7660bfc30c5e.png)

**Comment by siddontang** [comment]
seem that you find the user with id 11?

**Comment by itarafath** [comment]
Yeah. That's newly inserted one. But existing data are missing.

**Comment by siddontang** [comment]
what is your existing data? can you show me an example, like selecting the result in MySQL and then in ES?

**Comment by itarafath** [comment]
![image](https://cloud.githubusercontent.com/assets/1159869/20086931/379d1c28-a59a-11e6-8d5f-aaf137ee825c.png)

**Comment by siddontang** [comment]
how about `curl -XGET "http://localhost:9200/users/user/1"` or `curl -XGET "http://localhost:9200/users/user/11"`

**Comment by itarafath** [comment]
![image](https://cloud.githubusercontent.com/assets/1159869/20089236/6abd5300-a5ab-11e6-9f90-2687737ec453.png)

**Comment by siddontang** [comment]
very strange. I will dive this issue later.
Can you show me the user table schema in MySQL. 
What's your MySQL version, your ES version?

**Comment by itarafath** [comment]
MySQL : 5.6.21
ES : 5.0.0

Table Schema
`CREATE TABLE `a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;`

**Comment by siddontang** [comment]
Hi @itarafath 

I use your config and data to test in my Mac OSX. But to my surprised, it works ok. 

1. Create the table `a` and insert `(1, name1)` and `(2, name2)`. 
2. Use `reset master` to force MySQL clear its binlog. 
3. Start go-mysql-elasticsearch with your configuration. 

    ```bash
    ➜  go-mysql-elasticsearch git:(master) ✗ ./bin/go-mysql-elasticsearch -config etc/river.toml
    2016/11/10 20:21:44 binlogsyncer.go:71: [info] create BinlogSyncer with config &{1001 mysql 127.0.0.1 3306 root   false false}
    2016/11/10 20:21:44 dump.go:108: [info] try dump MySQL and parse
    2016/11/10 20:21:44 status.go:52: [info] run status http server 127.0.0.1:12800
    mysqldump: [Warning] Using a password on the command line interface can be insecure.
    2016/11/10 20:21:45 dump.go:114: [info] dump MySQL and parse OK, use 1.29 seconds, start binlog replication at (mysql.000001, 154)
    2016/11/10 20:21:45 sync.go:17: [info] start sync binlog at (mysql.000001, 154)
    2016/11/10 20:21:45 binlogsyncer.go:226: [info] begin to sync binlog from position (mysql.000001, 154)
    2016/11/10 20:21:45 binlogsyncer.go:130: [info] register slave for master server 127.0.0.1:3306
    2016/11/10 20:21:45 binlogsyncer.go:552: [info] rotate to (mysql.000001, 154)
    2016/11/10 20:21:45 sync.go:53: [info] rotate binlog to (mysql.000001, 154)
    ```
 
4. Select in ES

    ```bash
    curl -XGET "http://localhost:9200/users/user/1"
    {"_index":"users","_type":"user","_id":"1","_version":1,"found":true,"_source":{"id":1,"name":"name1"}}
    ```

5. Insert `(3, name3)` and select in ES

    ```bash
    curl -XGET "http://localhost:9200/users/user/3"
    {"_index":"users","_type":"user","_id":"3","_version":1,"found":true,"_source":{"id":3,"name":"name3"}}
    ```

I use MySQL 5.7.16 and ES 5.0.0. 
I don't know what is wrong in your test now......

**Comment by itarafath** [comment]
@siddontang Ok. I will try . Thanks for your support . 👍
