### ISSUE TITLE
同步失败

### ISSUE THREAD

**Issue by huangxiaoye** [siddontang/go-mysql-elasticsearch#66]
2016/11/14 17:52:07 binlogsyncer.go:71: [info] create BinlogSyncer with config &{1 mysql 192.168.0.3 3336 test test  false false}
github.com/siddontang/go-mysql/canal/canal.go:242: binlog must ROW format, but STATEMENT now
github.com/siddontang/go-mysql/canal/canal.go:84: 
F:/gocode/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:82: 
F:/gocode/src/github.com/siddontang/go-mysql-elasticsearch/river/river.go:44:

**Comment by siddontang** [comment]
see `binlog must ROW format, but STATEMENT now`
you must use binlog ROW format, not STATEMENT.

**Comment by niaiwomattt** [comment]
Are you exporting with MySQLdump?
Why not set it in parameters?
And let the user configure the server?
