### ISSUE TITLE
sync data from mysql how to filter columns

### ISSUE THREAD

**Issue by huangxiaoye** [siddontang/go-mysql-elasticsearch#68]
How to sync data from mysql use custom sql? For example I have user table 4 columns (id,username,nicknane,passowd) but I dont sync password to es. Any ideas? thanks

**Comment by siddontang** [comment]
Supply a filter column configs and don't sync may be ok. but I have no time to add it now. Could you send me a PR?

**Comment by huangxiaoye** [comment]
I'm really sorry,I dont know about golang.
