### ISSUE TITLE
Please add field filtering ASAP.

### ISSUE THREAD

**Issue by newyangyang** [siddontang/go-mysql-elasticsearch#73]
This is a great work, thank you for your effort. 
But I strongly recommend adding the field filtering feature asap.
The most common scenario to use go-mysql-elasticsearch is : mysql as the database, ES as the search engine, go-mysql-elasticsearch as the bridge. Only searchable text fields are needed to be synchronized, but now I have to change ES and go-mysql-elasticsearch config everytime mysql scheme is changed.
Thanks in advance.

**Comment by dangyuluo** [comment]
Sounds reasonable.

**Comment by siddontang** [comment]
Already supported, see https://github.com/siddontang/go-mysql-elasticsearch/blob/master/etc/river.toml#L88

I will add this to the README later.
