### ISSUE TITLE
json数据同步问题

### ISSUE THREAD

**Issue by beetle-p** [siddontang/go-mysql-elasticsearch#74]
您好，我现在遇到一个问题，mariadb里用varchar存放的json数据:
{"id":"17554578148691968"}
初次启动同步进ES里的数据显示为，多了一个"\\":
{\\"id\":\\"17554578148691968\\"}
后续新增的数据同步却又显示正常，见下图：
![image](https://cloud.githubusercontent.com/assets/23712738/20586380/5c44dd26-b23e-11e6-9978-f6f404b379c2.png)

**Comment by siddontang** [comment]
初次可能同步的 mysqldump 生成的数据，后面走的是 mysql binlog。

可能 mysqldump 没处理好。后续有时间我看看

**Comment by beetle-p** [comment]
这个问题，现在有修复的计划么

**Comment by siddontang** [comment]
No time now :sob: 

Try to fix it next week.

**Comment by siddontang** [comment]
Hi @beetle-p 

I have already created a PR https://github.com/siddontang/go-mysql/pull/104 to solve this. 

I will update this project later.

**Comment by siddontang** [comment]
Fixed
