### ISSUE TITLE
it's  frequently crash 

### ISSUE THREAD

**Issue by hzruandd** [siddontang/go-mysql-elasticsearch#76]
tail -n 200 nohup.out:

2016/12/08 15:51:05 binlogsyncer.go:71: [info] create BinlogSyncer with config &{100 mysql 10.8.6.xxx 3306 jake 123456  false false}
2016/12/08 15:51:15 status.go:52: [info] run status http server 10.8.6.xxx:12800
2016/12/08 15:51:15 dump.go:96: [info] skip dump, use last binlog replication pos (mysql-bin.000001, 9563365)
2016/12/08 15:51:15 sync.go:17: [info] start sync binlog at (mysql-bin.000001, 9563365)
2016/12/08 15:51:15 binlogsyncer.go:226: [info] begin to sync binlog from position (mysql-bin.000001, 9563365)
2016/12/08 15:51:15 binlogsyncer.go:130: [info] register slave for master server 10.8.6.xxx:3306
2016/12/08 15:51:25 binlogsyncer.go:552: [info] rotate to (mysql-bin.000001, 9563365)
2016/12/08 15:51:25 sync.go:53: [info] rotate binlog to (mysql-bin.000001, 9563365)
2016/12/08 18:31:09 river.go:249: [info] closing river
2016/12/08 18:31:09 canal.go:164: [info] close canal
2016/12/08 18:31:09 binlogsyncer.go:98: [info] syncer is closing... 
2016/12/08 18:31:09 binlogsyncer.go:481: [error] connection was bad 
2016/12/08 18:31:09 binlogstreamer.go:47: [error] close sync with err: Sync was closed
2016/12/08 18:31:09 binlogsyncer.go:113: [info] syncer is closed 

i find it frequently crash, but there is nothing could be found  from the  log  or nohup.out.

**Comment by siddontang** [comment]
Seem that you got a SIGNAL to quit the program. 
Even you start with nohup, you may receive a quit signal when your session closes.
