### ISSUE TITLE
canal start sync binlog err: ERROR 1236 (HY000): Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by everlytics** [siddontang/go-mysql-elasticsearch#78]
I have installed go-mysql-elasticsearch one month back.Sync was working fine.But now it sync stopped due to some mysql binlog file missing error.Please see below full error  message

![binlog](https://cloud.githubusercontent.com/assets/21295402/21262978/3cec7c94-c3ba-11e6-982b-1cbf1ef23648.png)

I have set mysql log  expiry to 10 days.Now mysql have following files

![binlog2](https://cloud.githubusercontent.com/assets/21295402/21263065/a3c83192-c3ba-11e6-8582-f9c8629ad8fe.png)

mysql-bin.index has entry 

![binlog3](https://cloud.githubusercontent.com/assets/21295402/21263118/ed56887c-c3ba-11e6-8a8d-8c61aefb8436.png)

I could not understand why go-mysql-elasticsearch is searching for mysql-bin.000039 when it is deleted.I even tried changing river.toml  in different way.
I have to fix this as soon as possible.Can any one  help me to fix this please?

**Comment by siddontang** [comment]
Hi @everlytics 

go-mysql-elasticsearch saved your last sync position in `$data_dir/master.info`, the `data_dir` is set in your config file. 

You can change `bin_name` to the binlog name you want to sync first. 
Btw, you may still set `bin_pos` to 4 if possible or any offset you want to start from.

**Comment by everlytics** [comment]
Thank you very much!.
I have set both bin_name and bin_pos  then it works fine for me.May I know the reason for why it as stoped syncing.I have to avoid this to be happen in future.

**Comment by siddontang** [comment]
go-mysql-elasticsearch will read the binlog name and pos in the master.info for syncing, but the binlog file is deleted in MySQL, so go-mysql-elasticsearch can't sync.
