### ISSUE TITLE
Parent-child relationship help

### ISSUE THREAD

**Issue by ebisrat** [siddontang/go-mysql-elasticsearch#81]
I was using your library to ElasticSearch and I am able to create a basic index for my tables. But I was having trouble creating the Parent-Child relationship, using the example you have in the rule config section. 

In my example I have 2 tables: organization and promotion. The promotion table has a has a field named organization_id that has 1 to 1 relationship with organization. How do I properly create the river.toml for this?

# MySQL data source
[[source]]
schema = "test"
tables = ["organization", "promotion"]

[[rule]]
schema = "test"
table = "promotion"
index = "promo"
type = "promo"
parent = "organization_id"

**Comment by EagleChen** [comment]
@ebisrat  
Did you manually set up the index mapping in ElasticSearch?

If not, you need to set them correctly first. Please refer to [this doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-parent-field.html) on how to set up the relationship. Basically, you need to set:
```
"mappings": {
    "promotion": {
        "_parent": { "type":  "organization"},
       ....
    }
}
```

This library will help you "exporting" data to  ElasticSearch and set the "_parent" part for each document( one row in mysql ). But you need to specify the relationship explicitly in the first place.

Hope my answer will help you.

**Comment by eyobebisrat** [comment]
@EagleChen Ok I see. I was able to create the correct ES mapping.

`{"promotion":{"mappings":{"promotion":{"_all":{"enabled":false},"_parent":{"type":"organization"},"_routing":{"required":true}}}}}`

 Now that I have set up the correct index/_parent mapping in ES, can you tell the correct way to setup the river.toml so that "organization_id" of the table organization in turn populates promotion's index "_parent".

**Comment by EagleChen** [comment]
@ebisrat 

Then the configuration in your first question is right.
```
[[rule]]
schema = "test"
table = "promotion"
index = "promotion"
type = "promotion"
parent = "organization_id"
```

By the way, you need to put `promotion`(type) and `organization`(type) in the same index.

**Comment by G-Bruin** [comment]
> @ebisrat
> 
> Then the configuration in your first question is right.
> 
> ```
> [[rule]]
> schema = "test"
> table = "organization"
> index = "promotion"
> type = "organization"
> 
> [[rule]]
> schema = "test"
> table = "promotion"
> index = "promotion"
> type = "promotion"
> parent = "organization_id"
> ```
> 
> By the way, you need to put `promotion`(type) and `organization`(type) in the same index.
elastic 5.5:
how to make elastic mapping ?
