### ISSUE TITLE
mysql中的中文同步到es显示为乱码

### ISSUE THREAD

**Issue by WangXiangUSTC** [siddontang/go-mysql-elasticsearch#89]
mysql中DEFAULT CHARSET=latin1，某个字段为varchar类型，包含中文。
在同步到elasticsearch后变成乱码，"ä¸€å°å †é’»çŸ³"。

**Comment by siddontang** [comment]
你试试 utf-8 charset 会不会也是一样的问题？go-mysql-elasticsearch 不会处理编码问题，都是 binary 直接扔给 ES 的，所以需要看 ES 的编码这些。

**Comment by WangXiangUSTC** [comment]
mysqldump 可以设置参数--default-character-set=latin1，这样显示就不是乱码了，是否可以在配置文件里加一个参数，自己设置字符集

**Comment by siddontang** [comment]
欢迎提 PR :-)
